server:
  retention: 15d
  persistentVolume:
    size: 50Gi
    storageClass: standard

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname', 'instance']
      group_wait: 10s
      group_interval: 5m
      repeat_interval: 4h
      receiver: 'slack-notifications'
    receivers:
    - name: 'slack-notifications'
      slack_configs:
      - api_url: 'https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK'
        channel: '#alerts'
        send_resolved: true

ruleSelectorNilUsesHelmValues: false
ruleSelector: {}
ruleSelectorMatchLabels: {}
rules:
  groups:
  - name: social-analytics
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.1
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: High error rate detected
        description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.instance }}"

    - alert: HighLatency
      expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High latency detected
        description: "95th percentile latency is {{ $value }}s for {{ $labels.instance }}"

    - alert: HighCPUUsage
      expr: container_cpu_usage_seconds_total{container!=""} > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage detected
        description: "CPU usage is {{ $value | humanizePercentage }} for {{ $labels.container }}"

    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{container!=""} / container_spec_memory_limit_bytes{container!=""} > 0.8
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage detected
        description: "Memory usage is {{ $value | humanizePercentage }} for {{ $labels.container }}" 