# Настройки кластера
cluster.name: social-analytics
node.name: ${HOSTNAME}
network.host: 0.0.0.0
http.port: 9200
transport.port: 9300

# Настройки памяти
bootstrap.memory_lock: true
indices.memory.index_buffer_size: 30%

# Настройки безопасности
xpack.security.enabled: true
xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: certificate
xpack.security.transport.ssl.keystore.path: elastic-certificates.p12
xpack.security.transport.ssl.truststore.path: elastic-certificates.p12

# Настройки индексов
action.auto_create_index: .security,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*
action.master.node_timeout: 30s
action.support_unknown_indices: true

# Настройки поиска
search.max_buckets: 10000
search.max_keep_alive: 24h
search.allow_expensive_queries: true

# Настройки анализаторов
analysis:
  analyzer:
    russian:
      type: custom
      tokenizer: standard
      filter:
        - lowercase
        - stop
        - snowball
      char_filter:
        - html_strip
      stopwords: _russian_

# Настройки репликации
index.number_of_replicas: 1
index.number_of_shards: 5
index.refresh_interval: 1s

# Настройки мониторинга
xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true
xpack.monitoring.elasticsearch.collection.enabled: true

# Настройки логирования
logger.level: INFO
logger.type: file
logger.file: /var/log/elasticsearch/elasticsearch.log

# Настройки GC
bootstrap.system_call_filter: false
bootstrap.jvm.options: -Xms2g -Xmx2g -XX:+UseG1GC -XX:G1ReservePercent=25 -XX:InitiatingHeapOccupancyPercent=30

# Настройки путей
path.data: /usr/share/elasticsearch/data
path.logs: /var/log/elasticsearch
path.plugins: /usr/share/elasticsearch/plugins

# Настройки discovery
discovery.type: single-node
discovery.seed_hosts: ["elasticsearch"]
discovery.zen.minimum_master_nodes: 1
discovery.zen.ping_timeout: 3s
discovery.zen.commit_timeout: 30s

# Настройки gateway
gateway.recover_after_nodes: 1
gateway.recover_after_time: 5m
gateway.expected_nodes: 1 