global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8081']

  - job_name: 'social-integrator-service'
    static_configs:
      - targets: ['social-integrator-service:8082']

  - job_name: 'data-processing-service'
    static_configs:
      - targets: ['data-processing-service:8083']

  - job_name: 'analytics-service'
    static_configs:
      - targets: ['analytics-service:8084']

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:8085']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 