apiVersion: v1
kind: ConfigMap
metadata:
  name: datalake-config
  namespace: social-analytics
data:
  DATALAKE_TYPE: "s3"
  DATALAKE_ENDPOINT: "https://s3.${AWS_REGION}.amazonaws.com"
  DATALAKE_BUCKET: "social-analytics-data"
  DATALAKE_REGION: "${AWS_REGION}"
  DATALAKE_PATH_STYLE_ACCESS: "true"
  DATALAKE_COMPRESSION: "true"
  DATALAKE_PART_SIZE: "5242880"
  DATALAKE_MAX_CONNECTIONS: "50"
  DATALAKE_REQUEST_TIMEOUT: "30000"
  DATALAKE_CONNECTION_TIMEOUT: "30000"
  DATALAKE_RETRY_MAX_ATTEMPTS: "3"
  DATALAKE_RETRY_INITIAL_INTERVAL: "1000"
  DATALAKE_RETRY_MAX_INTERVAL: "10000"
  DATALAKE_RETRY_MULTIPLIER: "2"
  DATALAKE_RETRY_EXPONENTIAL_BACKOFF: "true"
  DATALAKE_ENCRYPTION: "true"
  DATALAKE_SERVER_SIDE_ENCRYPTION: "true"
  DATALAKE_ACL: "private"
  DATALAKE_CORS_ENABLED: "true"
  DATALAKE_CORS_ALLOWED_ORIGINS: "*"
  DATALAKE_CORS_ALLOWED_METHODS: "GET,PUT,POST,DELETE"
  DATALAKE_CORS_ALLOWED_HEADERS: "*"
  DATALAKE_CORS_EXPOSE_HEADERS: "ETag"
  DATALAKE_CORS_MAX_AGE: "3000"
  DATALAKE_VERSIONING_ENABLED: "true"
  DATALAKE_RAW_DATA_PREFIX: "raw-data"
  DATALAKE_PROCESSED_DATA_PREFIX: "processed-data"
  DATALAKE_TEMP_PREFIX: "temp"
  DATALAKE_BACKUP_PREFIX: "backup"
  DATALAKE_DATA_RETENTION_DAYS: "365"
  DATALAKE_BACKUP_RETENTION_DAYS: "90"
  DATALAKE_ENABLE_LIFECYCLE: "true"
  DATALAKE_LIFECYCLE_RULES: |
    - id: "delete-old-versions"
      status: "Enabled"
      noncurrentVersionExpiration:
        noncurrentDays: 30
    - id: "delete-old-data"
      status: "Enabled"
      expiration:
        days: 365
    - id: "transition-to-ia"
      status: "Enabled"
      transitions:
        - days: 90
          storageClass: "STANDARD_IA"
  DATALAKE_ENABLE_METRICS: "true"
  DATALAKE_METRICS_PREFIX: "datalake"
  DATALAKE_ENABLE_LOGGING: "true"
  DATALAKE_LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: Secret
metadata:
  name: datalake-credentials
  namespace: social-analytics
type: Opaque
data:
  DATALAKE_ACCESS_KEY: ${AWS_ACCESS_KEY_ID_BASE64}
  DATALAKE_SECRET_KEY: ${AWS_SECRET_ACCESS_KEY_BASE64}
  DATALAKE_KMS_KEY_ID: ${AWS_KMS_KEY_ID_BASE64} 