server:
  port: 8002

spring:
  application:
    name: data-processing-service
  data:
    mongodb:
      uri: mongodb://mongodb:27017/social_analytics
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin123
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

keycloak:
  auth-server-url: http://keycloak:8080
  realm: ${KEYCLOAK_REALM}
  resource: data-processing-service
  credentials:
    secret: ${KEYCLOAK_DATA_PROCESSING_SECRET}

logging:
  level:
    com.socialanalytics.dataprocessing: DEBUG 