server:
  port: 8002

spring:
  application:
    name: data-processing-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}
  cloud:
    discovery:
      enabled: false

eureka:
  client:
    enabled: false

keycloak:
  auth-server-url: ${KEYCLOAK_AUTH-SERVER-URL}
  realm: ${KEYCLOAK_REALM}
  resource: ${KEYCLOAK_RESOURCE}
  credentials:
    secret: ${KEYCLOAK_CREDENTIALS_SECRET}

logging:
  level:
    com.socialanalytics.dataprocessing: DEBUG 