apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-processing-service
  namespace: social-analytics
spec:
  replicas: 3
  selector:
    matchLabels:
      app: data-processing-service
  template:
    metadata:
      labels:
        app: data-processing-service
    spec:
      containers:
      - name: data-processing-service
        image: social-analytics/data-processing-service:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 2000m
            memory: 4Gi
        env:
        - name: SOCIAL_INTEGRATOR_URL
          value: "http://social-integrator:8080"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka:9092"
        - name: KAFKA_TOPIC_RAW_DATA
          value: "raw-data"
        - name: KAFKA_TOPIC_PROCESSED_DATA
          value: "processed-data"
        - name: SPARK_MASTER_URL
          value: "spark://spark-master:7077"
        - name: SPARK_EXECUTOR_MEMORY
          value: "2g"
        - name: SPARK_EXECUTOR_CORES
          value: "2"
        - name: BATCH_SIZE
          value: "1000"
        - name: PROCESSING_INTERVAL
          value: "300"
        - name: CACHE_TTL
          value: "3600"
        volumeMounts:
        - name: data-volume
          mountPath: /data
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 5
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: data-processing-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-processing-pvc
  namespace: social-analytics
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: data-processing-service-hpa
  namespace: social-analytics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: data-processing-service
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
---
apiVersion: networking.k8s.io/v1
kind: Service
metadata:
  name: data-processing-service
  namespace: social-analytics
spec:
  selector:
    app: data-processing-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 